create table if not exists public.menu_items (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  price integer not null check (price >= 0),
  description text not null default '',
  available boolean not null default true,
  image text not null default ''
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  table_number text not null,
  notes text not null default '',
  status text not null default 'Baru' check (status in ('Baru', 'Diterima', 'Diproses', 'Siap', 'Selesai')),
  created_at timestamptz not null default now(),
  items jsonb not null check (jsonb_typeof(items) = 'array')
);

alter table public.menu_items enable row level security;
alter table public.orders enable row level security;
grant select on public.menu_items to anon, authenticated;
grant insert, update, delete on public.menu_items to authenticated;
grant insert on public.orders to anon, authenticated;
grant select, update on public.orders to authenticated;
grant usage, select on sequence public.menu_items_id_seq to authenticated;
grant usage, select on sequence public.orders_id_seq to anon, authenticated;

drop policy if exists "Menu is readable by everyone" on public.menu_items;
create policy "Menu is readable by everyone"
  on public.menu_items for select
  to anon, authenticated
  using (true);

drop policy if exists "Admins manage menu" on public.menu_items;
create policy "Admins manage menu"
  on public.menu_items for all
  to authenticated
  using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
  with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists "Customers can place orders" on public.orders;
create policy "Customers can place orders"
  on public.orders for insert
  to anon, authenticated
  with check (status = 'Baru');

drop policy if exists "Admins read orders" on public.orders;
create policy "Admins read orders"
  on public.orders for select
  to authenticated
  using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists "Admins update orders" on public.orders;
create policy "Admins update orders"
  on public.orders for update
  to authenticated
  using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
  with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

insert into public.menu_items (id, name, category, price, description, available, image)
values
  (1, 'Caffè Latte', 'Coffee', 28000, 'Espresso lembut dengan susu creamy dan busa halus.', true, 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=900&q=80'),
  (2, 'Espresso', 'Coffee', 22000, 'Kopi hitam pekat dengan aroma roasted nutty.', true, 'https://images.unsplash.com/photo-1497636577773-f1231844b336?auto=format&fit=crop&w=900&q=80'),
  (3, 'Caramel Macchiato', 'Signature', 32000, 'Espresso, susu, dan caramel yang manis seimbang.', true, 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&w=900&q=80'),
  (4, 'Matcha Cloud', 'Non Coffee', 30000, 'Matcha creamy dengan tekstur lembut dan rasa earthy.', true, 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?auto=format&fit=crop&w=900&q=80'),
  (5, 'Toast Keju', 'Food', 26000, 'Roti panggang dengan keju meleleh dan sedikit herb.', true, 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=900&q=80'),
  (6, 'Nasi Goreng KopiKita', 'Food', 42000, 'Nasi goreng spesial dengan rasa gurih dan porsi hangat.', true, 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=900&q=80'),
  (7, 'Americano', 'Coffee', 24000, 'Espresso dengan air panas, ringan dengan karakter roasted yang bersih.', true, 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=900&q=80'),
  (8, 'Cappuccino', 'Coffee', 28000, 'Espresso seimbang dengan steamed milk dan foam yang lembut.', true, 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&w=900&q=80'),
  (9, 'Flat White', 'Coffee', 30000, 'Double espresso dengan microfoam halus dan rasa kopi yang lebih bold.', true, 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&w=900&q=80'),
  (10, 'Kopi Aren Latte', 'Signature', 28000, 'Espresso dan susu segar dengan manis alami gula aren.', true, 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&w=900&q=80'),
  (11, 'Sea Salt Caramel Latte', 'Signature', 34000, 'Latte lembut dengan caramel dan sentuhan sea salt.', true, 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&w=900&q=80'),
  (12, 'Chocolate Hazelnut', 'Non Coffee', 32000, 'Cokelat pekat dengan susu creamy dan aroma hazelnut.', true, 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?auto=format&fit=crop&w=900&q=80'),
  (13, 'Chicken Sandwich', 'Food', 38000, 'Roti panggang dengan ayam, sayuran segar, dan saus house-made.', true, 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=900&q=80'),
  (14, 'Butter Croissant', 'Food', 22000, 'Croissant berlapis dengan aroma butter dan tekstur renyah.', true, 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=900&q=80')
on conflict (id) do nothing;

select setval(
  pg_get_serial_sequence('public.menu_items', 'id'),
  greatest(coalesce((select max(id) from public.menu_items), 1), 1),
  true
);

-- Run this in the SQL editor after creating an admin user in Supabase Auth.
-- Replace the email before executing; app_metadata is not editable by the client.
-- update auth.users
-- set raw_app_meta_data = coalesce(raw_app_meta_data, '{}'::jsonb) || '{"role":"admin"}'::jsonb
-- where email = 'admin@example.com';
